[build-system]
requires = ["setuptools>=80", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "archivist"
dynamic = ["version"]
description = "Archival data storage for the Librarian"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "click",
    "fastapi",
    "numpy",
    "pydantic",
    "pydantic-settings",
    "sqlalchemy",
    "sqlalchemy-utils",
    "loguru",
    "uvicorn",
    "requests>=2.32.5",
    "alembic>=1.18.5",
]

[project.urls]
Homepage = "https://github.com/simonsobs/archivist"

[tool.setuptools_scm]
write_to = "src/archivist/_version.py"

[dependency-groups]
dev = [
    "coverage>=7.10.7",
    "coveralls>=4.0.1",
    "httpx>=0.28.1",
    "ipython>=9.15.0",
    "isort>=6.1.0",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "pytest-cov>=7.1.0",
    "pytest-random-order>=1.2.0",
    "ruff>=0.15.17",
]

[project.scripts]
archivist = "archivist.__main__:main"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = ["ANN001",
          "SIM118",
          "T201",
          "D100",
          "INP001",
          "D212",
          "PTH119",
          "D415",
          "D103",
          "D411",
          "D410",
          "COM812",
          "D205",
          "S101",
          "D202",
          "SLF001",
          "D401",
          "D400",
          "FBT001",
          "ANN202",
          "PTH123",
          "FBT002",
          "ANN201",
          "F401",
          "F841"
]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 80

[tool.ruff.lint.per-file-ignores]
"**/scripts/*" = [
  "INP001",
  "T201",
]
"**/tests/**/*" = [
  "PLC1901",
  "PLR2004",
  "PLR6301",
  "S",
  "TID252",
  "T201",
  "DTZ005",
  "N802",
  "ARG005"
]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.isort]
known-first-party = ["archivist"]

[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false

[tool.isort]
profile = "black"
line_length = 120
skip = ["_version.py"]

[tool.pytest.ini_options]
addopts = "--random-order --cov=archivist --cov-report=term-missing --cov-report=xml"

[tool.coverage.run]
source = ["archivist"]
branch = true
