"""baseline: manifest, manifest_entry, archive

Revision ID: ff34fa3fb15c
Revises:
Create Date: 2026-07-13 11:12:15.020976

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff34fa3fb15c"

down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manifest",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("librarian_name", sa.String(length=256), nullable=False),
        sa.Column("created_time", sa.DateTime(), nullable=False),
        sa.Column("total_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("file_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "archive",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_time", sa.DateTime(), nullable=False),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("manifest_id", sa.String(length=36), nullable=False),
        sa.Column("archive_root", sa.String(length=512), nullable=False),
        sa.Column("archive_path", sa.String(length=2048), nullable=True),
        sa.Column("librarian_archive_id", sa.String(length=2048), nullable=True),
        sa.Column("consumed", sa.Boolean(), nullable=True),
        sa.Column("consumed_time", sa.DateTime(), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=True),
        sa.Column("completed_time", sa.DateTime(), nullable=True),
        sa.Column("failed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["manifest_id"], ["manifest.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("librarian_archive_id"),
        sa.UniqueConstraint("manifest_id"),
    )
    op.create_table(
        "manifest_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("manifest_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("checksum", sa.String(length=256), nullable=False),
        sa.Column("uploader", sa.String(length=256), nullable=False),
        sa.Column("source", sa.String(length=256), nullable=False),
        sa.Column("instance_path", sa.String(length=2048), nullable=False),
        sa.Column("instance_create_time", sa.DateTime(), nullable=False),
        sa.Column("instance_available", sa.Boolean(), nullable=False),
        sa.Column("outgoing_transfer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["manifest_id"], ["manifest.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("manifest_entry", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_manifest_entry_manifest_id"), ["manifest_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("manifest_entry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_manifest_entry_manifest_id"))

    op.drop_table("manifest_entry")
    op.drop_table("archive")
    op.drop_table("manifest")
    # ### end Alembic commands ###
