name: Test archivist

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --python ${{ matrix.python-version }} --group dev

      - name: Run tests
        run: |
          uv run pytest

      - name: Upload coverage report
        if: matrix.python-version == '3.11'
        run: uv run coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
